//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public string uid { get; set; }
        public string imid { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public string Genre { get; set; }
        public string Resolution { get; set; }
        public string Image { get; set; }
        public string Year { get; set; }
        public string Actor { get; set; }
    }
}
