//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myflix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public string uid { get; set; }
        public string imid { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string Language { get; set; }
        public string Genre1 { get; set; }
        public string Genre2 { get; set; }
        public string Genre3 { get; set; }
        public string Resolution { get; set; }
        public string Image { get; set; }
        public string Cast1 { get; set; }
        public string Cast2 { get; set; }
        public string Cast3 { get; set; }
        public string Cast4 { get; set; }
        public string Cast5 { get; set; }
        public Nullable<int> Views { get; set; }
    }
}
